version: "3.9"

name: paincare

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: paincare/api:latest
    container_name: paincare_api
    env_file:
      - .env
    environment:
      # Explicit defaults if not provided in .env
      API_HOST: 0.0.0.0
      API_PORT: 8000
      DEBUG_MODE: ${DEBUG_MODE:-false}
      # Firebase config
      FIREBASE_SERVICE_ACCOUNT_PATH: ${FIREBASE_SERVICE_ACCOUNT_PATH:-/app/firebase-service-account.json}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL:-}
    volumes:
      # Mount service account if present on host (optional). If omitted, the file from image will be used.
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
    networks:
      - paincare
    restart: unless-stopped

  management:
    build:
      context: .
      dockerfile: Dockerfile.management
    image: paincare/management:latest
    container_name: paincare_management
    env_file:
      - .env
    environment:
      DEBUG_MODE: ${DEBUG_MODE:-false}
      SECRET_KEY: ${SECRET_KEY:-change-me}
      FIREBASE_SERVICE_ACCOUNT_PATH: ${FIREBASE_SERVICE_ACCOUNT_PATH:-/app/firebase-service-account.json}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL:-}
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
      - ./logs:/app/logs
    depends_on:
      api:
        condition: service_healthy
    networks:
      - paincare
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: paincare_caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Email for Let's Encrypt notifications (optional but recommended)
      CADDY_EMAIL: ${CADDY_EMAIL:-}
      DOMAIN: ${DOMAIN:-paincare.vida-digital.tech}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      management:
        condition: service_started
      api:
        condition: service_started
    networks:
      - paincare
    restart: unless-stopped

networks:
  paincare:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
