version: "3.9"

name: paincare

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: paincare/api:latest
    container_name: paincare_api
    env_file:
      - .env
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8001
      DEBUG_MODE: ${DEBUG_MODE:-false}
      FIREBASE_SERVICE_ACCOUNT_PATH: ${FIREBASE_SERVICE_ACCOUNT_PATH:-/app/firebase-service-account.json}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL:-}
    ports:
      - "8001:8001"
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
    networks:
      - paincare
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/api/v1/health/liveness')"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s

  management:
    build:
      context: .
      dockerfile: Dockerfile.management
    image: paincare/management:latest
    container_name: paincare_management
    env_file:
      - .env
    environment:
      DEBUG_MODE: ${DEBUG_MODE:-false}
      SECRET_KEY: ${SECRET_KEY:-change-me}
      FIREBASE_SERVICE_ACCOUNT_PATH: ${FIREBASE_SERVICE_ACCOUNT_PATH:-/app/firebase-service-account.json}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL:-}
      MANAGEMENT_PORT: ${MANAGEMENT_PORT:-7000}
    ports:
      - "7000:7000"
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
      - ./logs:/app/logs
    depends_on:
      api:
        condition: service_healthy
    networks:
      - paincare
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 384M
        reservations:
          memory: 192M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/api/system/stats"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  paincare:
    driver: bridge
