version: '3.8'

services:
  paincare-ai:
    build: .
    container_name: paincare-ai-api
    ports:
      - "8000:8000"
    environment:
      - FIREBASE_SERVICE_ACCOUNT_PATH=/app/firebase-service-account.json
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG_MODE=False
      - LOG_LEVEL=INFO
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
      - ./logs:/app/logs
      - ./models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis
    networks:
      - paincare-network

  redis:
    image: redis:7-alpine
    container_name: paincare-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - paincare-network

  nginx:
    image: nginx:alpine
    container_name: paincare-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - paincare-ai
    restart: unless-stopped
    networks:
      - paincare-network

  prometheus:
    image: prom/prometheus:latest
    container_name: paincare-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - paincare-network

  grafana:
    image: grafana/grafana:latest
    container_name: paincare-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - paincare-network

volumes:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  paincare-network:
    driver: bridge
