version: "3.9"

name: paincare

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: paincare/api:latest
    container_name: paincare_api
    env_file:
      - .env
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8000
      DEBUG_MODE: ${DEBUG_MODE:-false}
      FIREBASE_SERVICE_ACCOUNT_PATH: ${FIREBASE_SERVICE_ACCOUNT_PATH:-/app/firebase-service-account.json}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL:-}
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
    networks:
      - paincare
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  management:
    build:
      context: .
      dockerfile: Dockerfile.management
    image: paincare/management:latest
    container_name: paincare_management
    env_file:
      - .env
    environment:
      DEBUG_MODE: ${DEBUG_MODE:-false}
      SECRET_KEY: ${SECRET_KEY:-change-me}
      FIREBASE_SERVICE_ACCOUNT_PATH: ${FIREBASE_SERVICE_ACCOUNT_PATH:-/app/firebase-service-account.json}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL:-}
      MANAGEMENT_PORT: ${MANAGEMENT_PORT:-7000}
    volumes:
      - ./firebase-service-account.json:/app/firebase-service-account.json:ro
      - ./logs:/app/logs
    depends_on:
      api:
        condition: service_healthy
    networks:
      - paincare
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  caddy:
    image: caddy:2
    container_name: paincare_caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Email for Let's Encrypt notifications (optional but recommended)
      CADDY_EMAIL: ${CADDY_EMAIL:-}
      DOMAIN: ${DOMAIN:-paincare.vida-digital.tech}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      management:
        condition: service_started
      api:
        condition: service_started
    networks:
      - paincare
    restart: unless-stopped

networks:
  paincare:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
